#!/bin/bash

for time in $(seq 1  1  20)
do 
    mkdir T$time
    cp holoQUADS_Heisenberg.jl  T$time/holoQUADS_Heisenberg.jl
    cp Entanglement.jl T$time/Entanglement.jl
    cp holoQUADS_Gates.jl T$time/holoQUADS_Gates.jl
    cp ObtainBond.jl T$time/ObtainBond.jl
    cp Sample_and_Measure.jl T$time/Sample_and_Measure.jl
    cp Sample.jl T$time/Sample.jl
    cp Projection.jl T$time/Projection.jl
    

    cp Generate_disBatch_Input_File.py T$time/Generate_disBatch_Input_File.py
    cd T$time
        mkdir Data

        # Linux version
        sed -i "s/floquet_time=1.0/floquet_time=$time/g" holoQUADS_Heisenberg.jl 
        sed -i "s/T0/T$time/g" Generate_disBatch_Input_File.py 

        # # MacOS version
        # sed -i "" "s/total_time=0.0/total_time=$time/g" holoQUADS_TEBD_SDKI.jl 
        # sed -i "" "s/T0/T$time/g" Generate_disBatch_Input_File.py    

        python3 Generate_disBatch_Input_File.py
         
        for index in $(seq 1  1  500)
        do
            mkdir Sample$index 
            cp holoQUADS_Heisenberg.jl  Sample$index/holoQUADS_Heisenberg.jl
            cd Sample$index
            
            random_number=$((RANDOM % 100000))
            # Linux version
            sed -i "s/sample_index=0/sample_index=$index/g" holoQUADS_Heisenberg.jl 
            sed -i "s/Random.seed!(123456)/Random.seed!($random_number)/g" holoQUADS_Heisenberg.jl

            # # MacOS version
            # sed -i "" "s/sample_index=0/sample_index=$index/g" holoQUADS_TEBD_SDKI.jl   
            # sed -i "" "s/Random.seed!(123)/Random.seed!($random_number)/g" holoQUADS_TEBD_SDKI.jl
            cd ..
        done

        for tmp_index in $(seq 1  1  2)
        do
            cp Generate_disBatch_Input_File.py Generate_disBatch_Input_File$tmp_index.py

            # Linux version
            sed -i "s/T0/T$time_$tmp_index/g" Generate_disBatch_Input_File$tmp_index.py
            sed -i "s/sample_seed=0/sample_seed=$tmp_index/g" Generate_disBatch_Input_File$tmp_index.py

            # # MacOS version
            # sed -i "" "s/T0/T$time_$tmp_index/g" Generate_disBatch_Input_File$tmp_index.py
            # sed -i "" "s/sample_seed=0/sample_seed=$tmp_index/g" Generate_disBatch_Input_File$tmp_index.py

            python3 Generate_disBatch_Input_File$tmp_index.py

             # Job submission on rusty
            sbatch -n 250 -c 8 -t 7-0:0:0 -p ccq --constraint=rome disBatch T$time

            # # Job submission on popeye
            # sbatch -n 500 -c 4 -t 7-0:0:0 -p ccq --constraint=cascadelake disBatch T$time 
        done
    cd ..   
done