#!/bin/bash

for index in $(seq 1  1  500)
do
    mkdir Sample$index 
    cp holoQUADS_SDKI.jl  Sample$index/holoQUADS_SDKI.jl
    cd Sample$index
    
    random_number=$((RANDOM % 100000))
    # Linux version
    sed -i "s/sample_index=0/sample_index=$index/g" holoQUADS_SDKI.jl 
    sed -i "s/Random.seed!(123)/Random.seed!($random_number)/g" holoQUADS_SDKI.jl

    # # MacOS version
    # sed -i "" "s/sample_index=0/sample_index=$index/g" holoQUADS_SDKI.jl   
    # sed -i "" "s/Random.seed!(123)/Random.seed!($random_number)/g" holoQUADS_SDKI.jl
    cd ..
done