#!/bin/bash
mkdir Data/
python3 Generate_disBatch_Input_File.py

for index in $(seq 1  1  500)
do
    mkdir Sample$index 
    cp holoQUADS_TEBD_SDKI.jl  Sample$index/holoQUADS_TEBD_SDKI.jl
    cd Sample$index
    
    random_number=$((RANDOM % 100000))
    # Linux version
    sed -i "s/sample_index=0/sample_index=$index/g" holoQUADS_TEBD_SDKI.jl 
    sed -i "s/Random.seed!(123)/Random.seed!($random_number)/g" holoQUADS_TEBD_SDKI.jl

    # # MacOS version
    # sed -i "" "s/sample_index=0/sample_index=$index/g" holoQUADS_SDKI.jl   
    # sed -i "" "s/Random.seed!(123)/Random.seed!($random_number)/g" holoQUADS_SDKI.jl
    cd ..
done

# Job submission on rusty
sbatch -n 500 -c 1 -t 7-0:0:0 -p ccq --constraint=rome disBatch T5